import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-Hant">
      <body className="bg-gray-50 min-h-screen font-sans">
        <header className="w-full py-4" style={{background:'#ff8800', color:'#fff'}}>
          <div className="text-center text-xl font-bold shadow">ICOPE 長者功能評估問卷系統</div>
        </header>
        <main className="max-w-3xl mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
